# -*- coding: utf-8 -*-
"""Resume_Screening_Using_RAG_ChromaDB_LLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wCpeIxWskoQ_pUu496gdeoj879Za_WKO
"""

!pip install -q chromadb sentence-transformers pypdf langchain langchain-community transformers accelerate bitsandbytes langchain-text-splitters

import chromadb
import sentence_transformers
import transformers

print("All libraries loaded successfully!")

from google.colab import files

uploaded = files.upload()

from pypdf import PdfReader

documents = []

# Use the actual uploaded filenames
pdf_files = list(uploaded.keys())

for pdf in pdf_files:
    reader = PdfReader(pdf)

    text = ""

    for page in reader.pages:
        text += page.extract_text()

    documents.append(text)

print("Loaded", len(documents), "resumes")

from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)

chunks = []

for doc in documents:
    chunks.extend(splitter.split_text(doc))

print("Total Chunks:", len(chunks))

from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2"
)

embeddings = embedding_model.encode(chunks)

import chromadb

client = chromadb.Client()

collection = client.create_collection(
    name="resume_collection"
)

for i, chunk in enumerate(chunks):
    collection.add(
        ids=[str(i)],
        documents=[chunk],
        embeddings=[embeddings[i].tolist()]
    )

print("Stored in ChromaDB")

from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline

model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto"
)

generator = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=200
)

print("LLM Loaded")

def retrieve(query, top_k=3):

    query_embedding = embedding_model.encode([query])[0]

    results = collection.query(
        query_embeddings=[query_embedding.tolist()],
        n_results=top_k
    )

    return results["documents"][0]

def rag(query):

    retrieved_docs = retrieve(query)

    context = "\n\n".join(retrieved_docs)

    prompt = f"""
Use the resume information below.

Context:
{context}

Question:
{query}

Answer:
"""

    result = generator(prompt)

    return result[0]["generated_text"]

query = "Who has experience in Machine Learning?"

answer = rag(query)

print(answer)

rag("Who knows Python?")

rag("Compare all three candidates")

rag("Which resume is best suited for Data Scientist role?")